const products = [
  {id:1,name:'Cloud Runner',category:'men',price:145,img:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=85',tag:'Bestseller',desc:'A lightweight everyday runner with responsive cushioning and a breathable knit upper.'},
  {id:2,name:'Forma Slide',category:'women',price:95,img:'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=700&q=85',tag:'New',desc:'Minimal, sculptural and surprisingly comfortable. Your new off-duty essential.'},
  {id:3,name:'Daybreak Low',category:'men',price:130,img:'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=700&q=85',tag:'',desc:'A classic low-top reimagined in soft, durable materials for everyday adventures.'},
  {id:4,name:'Mira Knit',category:'women',price:155,img:'https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=700&q=85',tag:'Bestseller',desc:'Effortless slip-on comfort with a sock-like fit and cloud-soft footbed.'},
  {id:5,name:'Mini Sprint',category:'kids',price:75,img:'https://images.unsplash.com/photo-1514989940723-e8e87e3c6d1a?auto=format&fit=crop&w=700&q=85',tag:'',desc:'Playground-ready sneakers that are easy to put on and built for big imaginations.'},
  {id:6,name:'Trail Form',category:'kids',price:85,img:'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=700&q=85',tag:'New',desc:'Grippy, flexible and ready for wherever the day takes them.'}
];
let cart = [], selectedProduct = null, selectedSize = 'M';
const $ = s => document.querySelector(s);
function money(n){return `$${n.toFixed(2)}`}
function renderProducts(category='all'){$('#products').innerHTML=products.filter(p=>category==='all'||p.category===category).map(p=>`<article class="product-card"><div class="product-photo" data-id="${p.id}">${p.tag?`<span class="badge">${p.tag}</span>`:''}<img src="${p.img}" alt="${p.name} shoe"><span class="quick-view">QUICK VIEW + 360°</span></div><div class="product-meta"><div><h3>${p.name}</h3><p>${p.category[0].toUpperCase()+p.category.slice(1)} / Everyday</p></div><strong>${money(p.price)}</strong></div></article>`).join('');document.querySelectorAll('.product-photo').forEach(el=>el.onclick=()=>openProduct(+el.dataset.id))}
function openProduct(id){selectedProduct=products.find(p=>p.id===id);$('#modalCategory').textContent=selectedProduct.category.toUpperCase()+' / EVERYDAY';$('#modalName').textContent=selectedProduct.name;$('#modalPrice').textContent=money(selectedProduct.price);$('#modalDescription').textContent=selectedProduct.desc;$('#modalShoe').style.backgroundImage=`url('${selectedProduct.img}')`;$('#sizes').innerHTML=['S','M','L','XL'].map(s=>`<button class="${s===selectedSize?'active':''}" data-size="${s}">${s}</button>`).join('');document.querySelectorAll('#sizes button').forEach(b=>b.onclick=()=>{selectedSize=b.dataset.size;document.querySelectorAll('#sizes button').forEach(x=>x.classList.toggle('active',x===b))});$('#productModal').classList.add('open');$('#overlay').classList.add('open')}
function closeModals(){$('#productModal').classList.remove('open');$('#checkoutModal').classList.remove('open');if(!$('#cartDrawer').classList.contains('open'))$('#overlay').classList.remove('open')}
function addToCart(p=selectedProduct){let existing=cart.find(x=>x.id===p.id&&x.size===selectedSize);if(existing)existing.qty++;else cart.push({id:p.id,size:selectedSize,qty:1});renderCart();closeModals();showToast()}
function renderCart(){let count=cart.reduce((a,x)=>a+x.qty,0), total=cart.reduce((a,x)=>a+x.qty*products.find(p=>p.id===x.id).price,0);$('#cartCount').textContent=count;$('#drawerCount').textContent=`${count} ${count===1?'item':'items'}`;$('#subtotal').textContent=money(total);$('#payAmount').textContent=money(total);$('#checkoutBtn').disabled=!count;$('#cartItems').innerHTML=count?cart.map(x=>{let p=products.find(q=>q.id===x.id);return `<div class="cart-item"><img src="${p.img}" alt="${p.name}"><div><h3>${p.name}</h3><p>Size ${x.size} · Qty ${x.qty}</p><p>${money(p.price*x.qty)}</p><button class="remove" data-remove="${p.id}">Remove</button></div></div>`}).join(''):`<div class="empty-cart"><span>♧</span><p>Your bag is waiting.<br>Add something you love.</p></div>`;document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==+b.dataset.remove);renderCart()})}
function showToast(){let t=$('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
renderProducts();renderCart();
document.querySelectorAll('.category-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.category-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.category)});
$('#bagBtn').onclick=()=>{$('#cartDrawer').classList.add('open');$('#overlay').classList.add('open')};$('#closeCart').onclick=()=>{$('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('open')};$('#overlay').onclick=()=>{$('#cartDrawer').classList.remove('open');closeModals()};$('#closeProduct').onclick=closeModals;$('#closeCheckout').onclick=closeModals;$('#addFromModal').onclick=()=>addToCart();$('#checkoutBtn').onclick=()=>{$('#cartDrawer').classList.remove('open');$('#checkoutModal').classList.add('open');$('#overlay').classList.add('open')};$('#checkoutForm').onsubmit=e=>{e.preventDefault();cart=[];renderCart();closeModals();showToast();$('#toast').textContent='Order placed — thank you! ✓';setTimeout(()=>$('#toast').textContent='Added to your bag ✓',2600)};$('#newsletterForm').onsubmit=e=>{e.preventDefault();e.target.innerHTML='<p>Thanks for joining the movement. ✓</p>'};$('#menuBtn').onclick=()=>document.querySelector('.desktop-nav').classList.toggle('mobile-open');
let dragStart=0;$('#modalShoe').onpointerdown=e=>{dragStart=e.clientX;$('#modalShoe').setPointerCapture(e.pointerId)};$('#modalShoe').onpointermove=e=>{if(!dragStart)return;let diff=e.clientX-dragStart;if(Math.abs(diff)>35){$('#modalShoe').style.backgroundPosition=diff>0?'left center':'right center';dragStart=e.clientX}};$('#modalShoe').onpointerup=()=>dragStart=0;
